# Use custom format

[battery] # Works under 10% of battery
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

# Bugged?
[cmd_duration]
min_time = 5_000  # Show command duration over 1,000 milliseconds (=1 sec)
format = " took [$duration]($style)"
disabled = true

[directory]
read_only = " 󰌾"
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[hostname]
ssh_symbol = " "
format = "on [$hostname](bold yellow) "

[character]
#success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[line_break]
disabled = true

[localip]
disabled = false

[aws]
symbol = "  "

[c]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rust]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "